// // //Maincategory

// // export const ADD_MAINCATEGORY="CREATE_MAINCATEGORY"
// // export const ADD_MAINCATEGORY_RED="CREATE_MAINCATEGORY_RED"

// // export const GET_MAINCATEGORY="GET_MAINCATEGORY"
// // export const GET_MAINCATEGORY_RED="GET_MAINCATEGORY_RED"

// // export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
// // export const UPDATE_MAINCATEGORY_RED="UPDATE_MAINCATEGORY_RED"

// // export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
// // export const DELETE_MAINCATEGORY_RED="DELETE_MAINCATEGORY_RED"


// Maincategory

// export const ADD_MAINCATEGORY="CREATE_MAINCATEGORY"
// export const ADD_MAINCATEGORY_RED="CREATE_MAINCATEGORY_RED"
// export const GET_MAINCATEGORY="GET_MAINCATEGORY"
// export const GET_MAINCATEGORY_RED="GET_MAINCATEGORY_RED"
// export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
// export const UPDATE_MAINCATEGORY_RED="UPADTE_MAINCATEGORY_RED"
// export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
// export const DELETE_MAINCATEGORY_RED="DELETE_MAINCATEGORY_RED"



//Maincategory 

export const ADD_MAINCATEGORY="CREATE_MAINCATEGORY"
export const ADD_MAINCATEGORY_RED="CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY="GET_MAINCATEGORY"
export const GET_MAINCATEGORY_RED="GET_MAINCATEGORY_RED"
export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED="UPDATE_MAINCATEGORY_RED"
export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED="DELETE_MAINCATEGORY_RED"

